<h3>{TITLE}</h3>
{SHOW_ANN}{SHOW_ANN_LABEL}<br />
{SHOW_PAST_ANN}{SHOW_PAST_ANN_LABEL}<br /><br />

{NUM_HOME_ANN}{NUM_HOME_ANN_LABEL}<br />
{NUM_PAST_ANN}{NUM_PAST_ANN_LABEL}<br /><br />
{SUBMIT} {UPDATE_FATCAT}
